'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Chess } from 'chess.js';
import styles from './ChessEgg.module.css';
type Promotion='q'|'r'|'b'|'n'; type Move={from:string;to:string;promotion?:Promotion;san?:string;captured?:string}; type Difficulty='easy'|'normal'|'hard'|'expert'; type Side='w'|'b'; type Clock='none'|5|10|15|30; type PlayAs='random'|'w'|'b';
const files=['a','b','c','d','e','f','g','h']; const START_FEN=new Chess().fen(); const pawnPath='M12 3c-2 0-3 2-3 4 0 1 .5 2 1.5 2.7C8 10.5 6 13 6 16h12c0-3-2-5.5-4.5-6.3C14.5 9 15 8 15 7c0-2-1-4-3-4Zm-5 15h10v3H7z'; const glyph:Record<string,string>={r:'♜',n:'♞',b:'♝',q:'♛',k:'♚'}; const value:Record<string,number>={p:100,n:320,b:330,r:500,q:900,k:20000};
function PieceIcon({type,color}:{type:string;color:'w'|'b'}){if(type==='p')return <svg className={`${styles.piece} ${color==='w'?styles.whitePiece:styles.blackPiece}`} viewBox="0 0 24 24"><path d={pawnPath}/></svg>;return <span className={`${styles.pieceGlyph} ${color==='w'?styles.whitePiece:styles.blackPiece}`}>{glyph[type]}</span>}
function attacked(g:Chess,sq:string,by:Side){return g.isAttacked(sq as any,by)}
function evaluate(g:Chess,ai:Side,d:Difficulty){const opponent=ai==='w'?'b':'w';if(g.isCheckmate())return g.turn()===ai?-1000000:1000000;let score=0;for(const row of g.board())for(const p of row)if(p)score+=(p.color===ai?1:-1)*value[p.type];if(d==='expert'){const king=g.board().flat().find(p=>p?.type==='k'&&p.color===ai);const enemyKing=g.board().flat().find(p=>p?.type==='k'&&p.color===opponent);if(king){const sq=Object.keys({}).length; void sq;}
 const aiKingSq=g.board().flatMap((row,r)=>row.map((p,c)=>p?.type==='k'&&p.color===ai?`${files[c]}${8-r}`:null)).find(Boolean); const enemyKingSq=g.board().flatMap((row,r)=>row.map((p,c)=>p?.type==='k'&&p.color===opponent?`${files[c]}${8-r}`:null)).find(Boolean);
 if(aiKingSq){if(attacked(g,aiKingSq,opponent))score-=900; const near=g.moves({square:aiKingSq as any,verbose:true}).length;score-=Math.max(0,near-4)*8} if(enemyKingSq&&attacked(g,enemyKingSq,ai))score+=500;
 const rights=g.getCastlingRights(ai); if(rights.k||rights.q)score+=45;
 }
 return score}
function chooseAiMove(base:string,ai:Side,d:Difficulty){const g=new Chess(base);const moves=g.moves({verbose:true}) as Move[];if(!moves.length)return null;const scored=moves.map(m=>{const next=new Chess(base);try{next.move({from:m.from,to:m.to,promotion:m.promotion||'q'});return {m,score:evaluate(next,ai,d)}}catch{return {m,score:-Infinity}}});scored.sort((a,b)=>b.score-a.score);if(d!=='expert'){const count=d==='easy'?Math.min(10,scored.length):d==='normal'?Math.min(6,scored.length):Math.min(3,scored.length);return scored[Math.floor(Math.random()*count)].m} const top=scored.slice(0,Math.min(4,scored.length));return top[Math.floor(Math.random()*top.length)].m}
export default function ChessEgg({onClose}:{onClose:()=>void}){
 const [fen,setFen]=useState(START_FEN),[selected,setSelected]=useState<string|null>(null),[promotion,setPromotion]=useState<Move|null>(null),[status,setStatus]=useState('Choose your game.'),[thinking,setThinking]=useState(false),[lastMove,setLastMove]=useState<{from:string;to:string}|null>(null),[setup,setSetup]=useState(true),[difficulty,setDifficulty]=useState<Difficulty>('normal'),[side,setSide]=useState<Side>('w'),[playAs,setPlayAs]=useState<PlayAs>('random'),[clock,setClock]=useState<Clock>('none'),[whiteTime,setWhiteTime]=useState(0),[blackTime,setBlackTime]=useState(0),[drag,setDrag]=useState<{from:string;x:number;y:number}|null>(null); const timer=useRef<number|null>(null); const sideRef=useRef<Side>(side); const suppressClick=useRef(false); const boardRef=useRef<HTMLDivElement|null>(null); useEffect(()=>{sideRef.current=side},[side]); const game=useMemo(()=>new Chess(fen),[fen]); const board=game.board(); const displayBoard=side==='b'?[...board].reverse().map(row=>[...row].reverse()):board; const legal=useMemo(()=>selected&&game.turn()===side?game.moves({square:selected as any,verbose:true}) as Move[]:[],[game,selected,side]); const targets=new Set(legal.map(m=>m.to));
 const clearTimer=()=>{if(timer.current!==null){window.clearTimeout(timer.current);timer.current=null}}; useEffect(()=>()=>clearTimer(),[]);
 const finish=(g:Chess,m:Move,playerSide:Side)=>{setFen(g.fen());setLastMove({from:m.from,to:m.to});setSelected(null);setPromotion(null);setDrag(null);if(g.isCheckmate()){setStatus(g.turn()===playerSide?'Checkmate — Solomon wins.':'Checkmate — you win.');setThinking(false);clearTimer();return true}if(g.isStalemate()){setStatus('Stalemate.');setThinking(false);clearTimer();return true}if(g.isThreefoldRepetition()){setStatus('Draw — threefold repetition.');setThinking(false);clearTimer();return true}if(g.isDrawByFiftyMoves()){setStatus('Draw — 50-move rule.');setThinking(false);clearTimer();return true}if(g.isInsufficientMaterial()){setStatus('Draw — insufficient material.');setThinking(false);clearTimer();return true}const yourTurn=g.turn()===playerSide;setThinking(!yourTurn);setStatus(g.inCheck()?(yourTurn?'Check — your king is attacked.':'Check — Solomon is in check.'):(yourTurn?'Your move.':'Solomon is thinking…'));return false};
 const blackMove=(base:string,playerSide:Side)=>{const g=new Chess(base);if(g.isGameOver())return;const ai:Side=playerSide==='w'?'b':'w';if(g.turn()!==ai)return;const m=chooseAiMove(base,ai,difficulty);if(!m){setThinking(false);return}try{const played=g.move({from:m.from,to:m.to,promotion:m.promotion||'q'});finish(g,played as Move,playerSide)}catch{setThinking(false);setStatus('Your move.')}};
 const scheduleAI=(base:string,playerSide:Side)=>{clearTimer();const delay=difficulty==='easy'?650:difficulty==='normal'?1000:difficulty==='hard'?1500:2200;timer.current=window.setTimeout(()=>{timer.current=null;if(clock!=='none'&&(playerSide==='w'?blackTime:whiteTime)<=0){setThinking(false);setStatus('Time — game over.');return}blackMove(base,playerSide)},delay)};
 const commit=(m:Move)=>{try{const g=new Chess(fen);const playerSide=sideRef.current;const played=g.move({from:m.from,to:m.to,promotion:m.promotion});const over=finish(g,played as Move,playerSide);if(!over&&g.turn()!==playerSide)scheduleAI(g.fen(),playerSide)}catch{setSelected(null);setPromotion(null);setDrag(null)}};
 const start=()=>{clearTimer();const chosenSide:Side=playAs==='random'?(Math.random()<0.5?'w':'b'):playAs;sideRef.current=chosenSide;setSide(chosenSide);setFen(START_FEN);setSelected(null);setPromotion(null);setLastMove(null);setWhiteTime(clock==='none'?0:Number(clock)*60);setBlackTime(clock==='none'?0:Number(clock)*60);setSetup(false);if(chosenSide==='b'){setThinking(true);setStatus(difficulty==='expert'?'King Solomon is thinking…':'Solomon is thinking…');scheduleAI(START_FEN,chosenSide)}else{setThinking(false);setStatus(difficulty==='expert'?'Your move. King Solomon awaits.':'Your move.')}};
 const openNewGame=()=>{clearTimer();setSetup(true);setThinking(false);setStatus('Choose your game.');setSelected(null);setPromotion(null);setDrag(null)};
 useEffect(()=>{if(setup||clock==='none'||game.isGameOver())return;const id=window.setInterval(()=>{if(game.turn()==='w')setWhiteTime(t=>Math.max(0,t-1));else setBlackTime(t=>Math.max(0,t-1))},1000);return()=>window.clearInterval(id)},[fen,setup,clock,game]);
 useEffect(()=>{if(setup||clock==='none'||game.isGameOver())return;const activeTime=game.turn()==='w'?whiteTime:blackTime;if(activeTime<=0){clearTimer();setThinking(false);setStatus('Time — game over.')}},[whiteTime,blackTime,setup,clock,side,game]);
 const canInteract=()=>!setup&&!thinking&&!promotion&&!game.isGameOver()&&game.turn()===side;
 const choose=(sq:string)=>{if(!canInteract())return;const piece=game.get(sq as any);if(selected){const m=legal.find(x=>x.to===sq);if(m){if(m.promotion){setPromotion(m);return}commit(m);return}setSelected(piece?.color===side?sq:null);return}if(piece?.color===side)setSelected(sq)};
 const beginDrag=(sq:string,e:React.PointerEvent<HTMLButtonElement>)=>{if(!canInteract())return;const piece=game.get(sq as any);if(piece?.color!==side)return;e.preventDefault();setSelected(sq);setDrag({from:sq,x:e.clientX,y:e.clientY});suppressClick.current=true};
 const moveDrag=(e:React.PointerEvent<HTMLDivElement>)=>{if(!drag)return;e.preventDefault();setDrag(d=>d?{...d,x:e.clientX,y:e.clientY}:null)};
 const endDrag=(e:React.PointerEvent<HTMLDivElement>)=>{if(!drag)return;e.preventDefault();const from=drag.from;const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-chess-square]') as HTMLElement|null;const to=hit?.dataset.chessSquare||null;const m=to?legal.find(x=>x.to===to):undefined;setDrag(null);suppressClick.current=true;if(m){if(m.promotion){setPromotion(m);return}commit(m);return}if(to&&to!==from){setSelected(null)}};
 const promote=(type:Promotion)=>{if(!promotion||thinking)return;commit({...promotion,promotion:type})}; const fmt=(s:number)=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`; const dragPiece=drag?game.get(drag.from as any):null;
 return <div className={styles.overlay} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className={styles.modal}><button className={styles.close} onClick={onClose} aria-label="Close chess">×</button><div className={styles.top}><div><span className={styles.kicker}>SOLOMON</span><h2>{difficulty==='expert'?'♛ King Solomon':'Chess.'}</h2><p>{status}</p></div>{!setup&&<button className={styles.reset} onClick={openNewGame}>New game</button>}</div>{setup?<div className={styles.setup}><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value as Difficulty)}><option value="easy">Easy</option><option value="normal">Normal</option><option value="hard">Hard</option><option value="expert">King Solomon</option></select></label><label>Time<select value={clock} onChange={e=>setClock(e.target.value==='none'?'none':Number(e.target.value) as Clock)}><option value="none">No clock</option><option value="5">5 min</option><option value="10">10 min</option><option value="15">15 min</option><option value="30">30 min</option></select></label><label>Play as<select value={playAs} onChange={e=>setPlayAs(e.target.value as PlayAs)}><option value="random">Random — 50/50</option><option value="w">White</option><option value="b">Black</option></select></label><button className={styles.start} onClick={start}>Start Game</button></div>:<><div className={styles.clockRow}>{clock!=='none'&&<><span>White {fmt(whiteTime)}</span><span>Black {fmt(blackTime)}</span></>}</div><div ref={boardRef} className={styles.board} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={()=>setDrag(null)}>{displayBoard.map((row,r)=>row.map((piece,c)=>{const sq=side==='b'?`${files[7-c]}${1+r}`:`${files[c]}${8-r}`;return <button key={sq} data-chess-square={sq} className={`${styles.square} ${(r+c)%2?styles.dark:styles.light} ${lastMove?.from===sq||lastMove?.to===sq?styles.last:''} ${selected===sq?styles.selected:''} ${targets.has(sq)?styles.target:''}`} onPointerDown={e=>beginDrag(sq,e)} onClick={()=>{if(suppressClick.current){suppressClick.current=false;return}choose(sq)}}>{piece&&<PieceIcon type={piece.type} color={piece.color}/>}</button>}))}{drag&&dragPiece&&<div className={styles.dragPiece} style={{left:`${drag.x-(boardRef.current?.getBoundingClientRect().left||0)}px`,top:`${drag.y-(boardRef.current?.getBoundingClientRect().top||0)}px`}}><PieceIcon type={dragPiece.type} color={dragPiece.color}/></div>}</div>{promotion&&<div className={styles.promotion}><span>Promote pawn</span><div>{(['q','r','b','n'] as Promotion[]).map(t=><button key={t} onClick={()=>promote(t)}><PieceIcon type={t} color={side}/></button>)}</div></div>}</>}<div className={styles.note}>A hidden game for the curious. Nothing more. Nothing less.</div></div></div>}
